version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      - ConnectionString=${CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - identity-network

  db:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=2335
    networks:
      - identity-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - 5001:8080
    networks:
      - identity-network

networks:
  identity-network:
    driver: bridge